name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare
        run: pnpm prepare

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:coverage

      - name: Build
        run: pnpm build

      - name: Coverage
        uses: codecov/codecov-action@v3

      - name: Release
        if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'chore(release)')
        run: pnpm publish -q --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
